name: cifar100budget_Oort 100% # foldername_filename
num_rounds: 100
num_clients: 30
num_clients_per_round: 10
batch_size: 32
dataset: cifar100_dirichlet # cifar10_iid
alpha: 10 # for dirichlet

# client config:
config_fit:
  lr: 0.001
  local_epochs: 2
  weight_decay: # default = 0

# server config:
selection_strategy: oort # carbon_oort, oort else random
probing_round: 
threshold_coeff: 
carbon_intensities: True
add_curtailment_data: True
carbon_budget: True
total_carbon_budget: 50000000000000000000000
experiments:
  # corrupted clients
  start_round:
  until_round:
  data_damage:
  noise_std:
  num_defect_clients:
